export const SET_TWITTER_USER = 'SET_TWITTER_USER';
export const SET_TWEETS_FROM_USER = 'SET_TWEETS_FROM_USER';
export const SET_NGRAM_ORDER = 'SET_NGRAM_ORDER';
export const SET_NGRAM_TABLE = 'SET_NGRAM_TABLE';
export const SET_TWEET_TEXT = 'SET_TWEET_TEXT';
export const ADD_NEW_MARKOV_TWEET = 'ADD_NEW_MARKOV_TWEET';
export const RESET_MARKOVS = 'RESET_MARKOVS';